### ISSUE TITLE
Changing the gtk theme

### ISSUE THREAD

**Issue by OkulusDev** [myagko/nymph#9]
I objectively don't like the GTK theme. She stands out somehow.  And I expected compactness and minimalism from such a color scheme, and the GTK theme is too inconvenient for me. 
I created my own background version of gtk theme, which was created using oomox
[Uploading nymph-gtk.gz…]()

**Comment by OkulusDev** [comment]
My gtk theme generated with [oomox](https://github.com/themix-project/oomox-gtk-theme), fish shell syntax:
`./change_color.sh -o Nymph (echo -e "BG=1A2023\nBTN_BG=252B2E\nBTN_FG=BCC4C9\nFG=BCC4C9\nGRADIENT=0.0\nHDR_BTN_BG=373D40\nHDR_BTN_FG=BCC4C9\nHDR_BG=252B2E\nHDR_FG=BCC4C9\nROUNDNESS=0\nSEL_BG=5B6265\nSEL_FG=1A2023\nSPACING=3\nTXT_BG=373D40\nTXT_FG=BCC4C9\nWM_BORDER_FOCUS=9edc60\nWM_BORDER_UNFOCUS=0e0021\nACCENT_BG=1A2023" | psub)
`

**Comment by myagko** [comment]
> My gtk theme generated with [oomox](https://github.com/themix-project/oomox-gtk-theme), fish shell syntax: `./change_color.sh -o Nymph (echo -e "BG=1A2023\nBTN_BG=252B2E\nBTN_FG=BCC4C9\nFG=BCC4C9\nGRADIENT=0.0\nHDR_BTN_BG=373D40\nHDR_BTN_FG=BCC4C9\nHDR_BG=252B2E\nHDR_FG=BCC4C9\nROUNDNESS=0\nSEL_BG=5B6265\nSEL_FG=1A2023\nSPACING=3\nTXT_BG=373D40\nTXT_FG=BCC4C9\nWM_BORDER_FOCUS=9edc60\nWM_BORDER_UNFOCUS=0e0021\nACCENT_BG=1A2023" | psub) `

big thx dude, installed themix-gui, maybe i'll add gtk theme again soon

**Comment by OkulusDev** [comment]
i am close issue. Thanks for very good colorscheme!
